/// Flutter icons Iconx
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iconx
///      fonts:
///       - asset: fonts/Iconx.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class Iconx {
  Iconx._();

  static const _kFontFam = 'Iconx';

  static const IconData location = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData face = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData chat = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData home_1 = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData keypad = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData paper_plane = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData person_add = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData users = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData user_plus = IconData(0xf234, fontFamily: _kFontFam);
  static const IconData user_times = IconData(0xf235, fontFamily: _kFontFam);
}
